### PR TITLE
Make internal goal template respect year

### PR DESCRIPTION
**Pull request by lokal-profil**
Without the need for manually updating the config

Bug: [T242610](https://phabricator.wikimedia.org/T242610)

### CODE REVIEW

**Comment by lokal-profil** [comment]
Still needs to be tested

**Comment by lokal-profil** [comment]
The alternative is to make `<YEAR>` the first (unnamed) parameter of `Mall:Måltexter`. Until we change the whole goal structure that should mean less copy-pasting per year.

**Comment by lokal-profil** [comment]
> The alternative is to make `<YEAR>` the first (unnamed) parameter of `Mall:Måltexter`. Until we change the whole goal structure that should mean less copy-pasting per year.

This is definitely the way forward. Code wise should only require changing `Måltexter <YEAR>` to `Måltexter|<YEAR>`

**Comment by lokal-profil** [comment]
> The alternative is to make `<YEAR>` the first (unnamed) parameter of `Mall:Måltexter`. Until we change the whole goal structure that should mean less copy-pasting per year.

This is definitely the way forward. Code wise should only require changing `Måltexter <YEAR>` to `Måltexter|<YEAR>`

**Comment by lokal-profil** [comment]
> > The alternative is to make `<YEAR>` the first (unnamed) parameter of `Mall:Måltexter`. Until we change the whole goal structure that should mean less copy-pasting per year.
> 
> This is definitely the way forward. Code wise should only require changing `Måltexter <YEAR>` to `Måltexter|<YEAR>`

Done

**Review by sebastian-berlin-wmse — APPROVED** [review]

**Pull request merged**
